{% set name = "snpio" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://github.com/btmartin721/SNPio/archive/refs/tags/{{ version }}.tar.gz

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - biopython
    - bokeh
    - ete3
    - holoviews
    - kneed
    - matplotlib
    - numpy >=1.25
    - pandas >=2.0
    - panel
    - plotly
    - requests
    - cyvcf2
    - scikit-learn
    - scipy
    - seaborn
    - toytree
    - python-kaleido

about:
  home: https://github.com/btmartin721/SNPio
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Reads and writes VCF, PHYLIP, and STRUCTURE files and performs data filtering on the alignment.'

extra:
  recipe-maintainers:
    - btmartin721
    - tkchafin